#!/usr/bin/env python3
"""build_regenerate_script.py
Generates regenerate_all_inference_worlds.sh from the manifest CSV.
Avoids hand-maintaining the world list."""

import csv
import sys
from pathlib import Path


HEADER = '''#!/usr/bin/env bash
# AUTO-GENERATED by build_regenerate_script.py — do not hand-edit.
# Regenerates v7-inpaint reconstructions for ALL worlds in the manifest,
# using the train/test-fix flag --history-sparsify all_frames.
set -euo pipefail

PROJECT_ROOT="$(pwd)"
STAGE2_DIR="${PROJECT_ROOT}/AI_simulation/stage2"
CHECKPOINT="${PROJECT_ROOT}/stage2_outputs_new/checkpoints/best_model.pt"
TRUTH_DIR="${PROJECT_ROOT}/results/data"
OUT_BASE="${PROJECT_ROOT}/reconstructions_v7_inpaint"
RECON_SCRIPT="${STAGE2_DIR}/models/generate_reconstructions_v7_inpaint.py"

[[ -f "$CHECKPOINT" ]]   || { echo "✗ Checkpoint missing: $CHECKPOINT"; exit 1; }
[[ -f "$RECON_SCRIPT" ]] || { echo "✗ Recon script missing: $RECON_SCRIPT"; exit 1; }
grep -q "history-sparsify" "$RECON_SCRIPT" || {
    echo "✗ generate_reconstructions_v7_inpaint.py is missing the REV2 patch."
    echo "  It must contain the --history-sparsify flag (all_frames mode)."
    echo "  Apply the REV2 patch BEFORE running this script."
    exit 1
}

declare -a WORLDS=(
'''

FOOTER = ''')

SUCCESS=0; FAIL=0; SKIP=0; START_TIME=$SECONDS
total=${#WORLDS[@]}

echo ""
echo "==========================================================================="
echo "  REGENERATE INFERENCE  —  $total worlds, K=5 and K=10, all_frames mode"
echo "==========================================================================="
echo "  Checkpoint:  $CHECKPOINT"
echo "  Truth dir:   $TRUTH_DIR"
echo "  Output base: $OUT_BASE"
echo ""

for i in "${!WORLDS[@]}"; do
    world="${WORLDS[$i]}"
    stem="${world%.npz}"
    truth_path="${TRUTH_DIR}/${world}"
    out_dir="${OUT_BASE}_${stem}_stage2"
    idx=$((i + 1))

    echo ""
    echo "[${idx}/${total}] World: $world"
    echo "                  Out:   $out_dir"

    if [[ ! -f "$truth_path" ]]; then
        echo "    ✗ Truth NPZ missing — skipping"
        SKIP=$((SKIP + 1)); continue
    fi

    # Skip if already done with all_frames AND has both K=5 and K=10
    if [[ -f "${out_dir}/recon_fixed_b5_samples.npz" ]] && \\
       [[ -f "${out_dir}/recon_fixed_b10_samples.npz" ]]; then
        if python -c "
import numpy as np, sys
d = np.load('${out_dir}/recon_fixed_b5_samples.npz', allow_pickle=True)
sys.exit(0 if str(d.get('history_sparsify', 'unknown')) == 'all_frames' else 1)
" 2>/dev/null; then
            echo "    ✓ Already done with all_frames — skipping"
            SUCCESS=$((SUCCESS + 1)); continue
        else
            echo "    ⚠ Old run found (last_only or unknown) — regenerating"
        fi
    fi

    mkdir -p "$out_dir"

    if python "$RECON_SCRIPT" \\
        --stage2-dir         "$STAGE2_DIR" \\
        --checkpoint         "$CHECKPOINT" \\
        --truth-npz          "$truth_path" \\
        --output-dir         "$out_dir" \\
        --fixed-budgets      5 10 \\
        --mode               inpaint \\
        --repaint-iterations 2 \\
        --n-ensemble         8 \\
        --history-sparsify   all_frames \\
        --verbose; then
        echo "    ✓ Success [${idx}/${total}]"
        SUCCESS=$((SUCCESS + 1))
    else
        echo "    ✗ FAILED [${idx}/${total}]"
        FAIL=$((FAIL + 1))
    fi
done

ELAPSED=$((SECONDS - START_TIME))
H=$((ELAPSED / 3600))
M=$(( (ELAPSED % 3600) / 60 ))

echo ""
echo "==========================================================================="
echo "  COMPLETE"
echo "==========================================================================="
echo "  Success:  $SUCCESS"
echo "  Failed:   $FAIL"
echo "  Skipped:  $SKIP  (truth missing)"
echo "  Elapsed:  ${H}h ${M}m"
echo ""
echo "  Next: rerun the multi_world evaluation CSVs and the figures pipeline."
echo "==========================================================================="
'''


def main():
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <manifest.csv> <output_script.sh>")
        sys.exit(2)

    manifest_path = Path(sys.argv[1])
    output_path = Path(sys.argv[2])

    if not manifest_path.exists():
        print(f"✗ Manifest missing: {manifest_path}")
        sys.exit(1)

    with open(manifest_path) as f:
        rows = [r for r in csv.DictReader(f) if r.get("found") == "yes"]

    if not rows:
        print("✗ No rows with found=yes in manifest. Run pick_inference_worlds.py first.")
        sys.exit(1)

    rows.sort(key=lambda r: (r.get("batch", ""), r.get("label", "")))

    with open(output_path, "w") as f:
        f.write(HEADER)
        for r in rows:
            f.write(f'    "{r["filename"]}"   # {r["label"]:<22s} [{r["batch"]}]  {r["concern"]}\n')
        f.write(FOOTER)

    output_path.chmod(0o755)

    print(f"✓ Wrote {output_path} with {len(rows)} worlds")
    print(f"  Batches: A={sum(1 for r in rows if r['batch']=='A')}, "
          f"B={sum(1 for r in rows if r['batch']=='B')}")


if __name__ == "__main__":
    main()