# -----------------------------------------------------
# sweep_worlds_eval30.py  (AUTO-GENERATED by design_unseen_eval_worlds.py)
# -----------------------------------------------------
# Generates UNSEEN evaluation worlds at parameter combinations NOT in the
# training pool (NEW env seeds), with IDENTICAL IBM settings to sweep_worlds.py.
# After each world is generated, its output files are MOVED out of the raw
# results/data directory into the separate eval directory, so the training
# pool is never polluted.
#
# RUN FROM THE PROJECT ROOT (PSD_Dispersal_pool/) so that run_all_rps.py and
# results/ resolve correctly:
#     python scripts/sweep_worlds_eval30.py --limit 1     # smoke test
#     python scripts/sweep_worlds_eval30.py                # full run
# -----------------------------------------------------
import subprocess, os, sys, argparse, shlex, shutil
from pathlib import Path
from multiprocessing import Process


def get_gpu_list():
    cvd = os.environ.get("CUDA_VISIBLE_DEVICES")
    if cvd:
        return [g.strip() for g in cvd.split(",") if g.strip() != ""]
    try:
        import cupy as cp
        n = cp.cuda.runtime.getDeviceCount()
        return [str(i) for i in range(n)]
    except Exception:
        return ["0"]


# IDENTICAL base command to sweep_worlds.py — do not change.
base = [
    "python", "run_all_rps.py",
    "--pool", "22510000",
    "--skip-psd", "--skip-ode",
    "--tmax", "10000", "--record", "200", "--no-movie",
    "--ibm-frac-multi", "0.05",
    "--ibm-window-steps", "1000",
    "--ibm-max-attempts", "10000",
    "--ibm-richness-cap", "None",
    "--save-env-field",
    "--ibm-record-mode", "full",
    "--ibm-F-sat", "None",
    "--ibm-max-rounds", "None",
    "--save-every-rounds", "500",
    "--save-every-seconds", "600",
    "--C-topk", "16",
    "--coocc-sample", "4096",
    "--world-tag-extra", "batchA",
    "--fp16-time-series",
    "--obs-budgets", "1,5,10,20,50,100",
]

# (ls, vr, thr, env_seed, dr, ld) — env seeds are NEW (not in training pool)
EVAL_COMBOS = [
    (2.5, 0.004, 1.0, 789, 1e-07, 0.12),   # hardband [in_dist],
    (2.5, 0.004, 1.0, 2024, 1e-07, 0.12),   # hardband [in_dist],
    (2.5, 0.004, 3.0, 789, 1e-07, 0.12),   # hardband [in_dist],
    (2.5, 0.004, 3.0, 2024, 5e-08, 0.12),   # hardband [in_dist],
    (10.0, 0.001, 1.0, 789, 5e-08, 0.2),   # connectivity [in_dist],
    (10.0, 0.001, 1.0, 2024, 5e-08, 0.2),   # connectivity [in_dist],
    (10.0, 0.001, 3.0, 789, 1e-07, 0.2),   # connectivity [in_dist],
    (10.0, 0.001, 3.0, 2024, 1e-07, 0.2),   # connectivity [in_dist],
    (2.5, 0.004, 3.0, 789, 1e-07, 0.2),   # wide_range [in_dist],
    (5.0, 0.002, 3.0, 789, 1e-07, 0.2),   # wide_range [in_dist],
    (5.0, 0.002, 3.0, 2024, 1e-07, 0.2),   # wide_range [in_dist],
    (2.5, 0.002, 3.0, 2024, 1e-07, 0.2),   # wide_range [in_dist],
    (10.0, 0.002, 1.0, 789, 1e-07, 0.2),   # high_dispersal [in_dist],
    (10.0, 0.002, 1.0, 2024, 1e-07, 0.2),   # high_dispersal [in_dist],
    (5.0, 0.002, 1.0, 789, 1e-07, 0.2),   # high_dispersal [in_dist],
    (10.0, 0.004, 3.0, 2024, 1e-07, 0.2),   # high_dispersal [in_dist],
    (2.5, 0.004, 1.0, 789, 2e-08, 0.0),   # low_dispersal [in_dist],
    (5.0, 0.002, 1.0, 789, 2e-08, 0.0),   # low_dispersal [in_dist],
    (10.0, 0.001, 1.0, 2024, 2e-08, 0.0),   # low_dispersal [in_dist],
    (5.0, 0.002, 3.0, 2024, 2e-08, 0.0),   # low_dispersal [in_dist],
    (10.0, 0.001, 1.0, 789, 2e-08, 0.2),   # LDD [in_dist],
    (10.0, 0.001, 1.0, 2024, 2e-08, 0.2),   # LDD [in_dist],
    (5.0, 0.002, 1.0, 789, 2e-08, 0.2),   # LDD [in_dist],
    (5.0, 0.001, 3.0, 2024, 2e-08, 0.2),   # LDD [in_dist],
    (1.0, 0.004, 1.0, 789, 1e-07, 0.12),   # hardband_extrap [extrap],
    (2.5, 0.008, 3.0, 789, 1e-07, 0.2),   # variance_extrap [extrap],
    (10.0, 0.002, 1.0, 789, 2e-07, 0.2),   # ultra_high_disp_extrap [extrap],
    (10.0, 0.001, 1.0, 789, 5e-08, 0.3),   # ultra_LDD_extrap [extrap],
    (5.0, 0.002, 1.0, 789, 1e-08, 0.0),   # ultra_low_disp_extrap [extrap],
    (20.0, 0.001, 1.0, 789, 5e-08, 0.2),   # smooth_extrap [extrap]
]

RAW_DIR = Path("./results/data")          # where run_all_rps writes first
EVAL_DIR = Path("./results/data/data_eval_unseen")        # where we move the world (separate dir)


def _slug(x):
    if x is None:
        return "NA"
    return str(x).replace('.', 'p').replace('-', 'm')


def build_stem(ls, vr, thr, env, dr, ld):
    base_tag = "pool22510000_" + "batchA"
    tag = (base_tag
           + "_ls" + _slug(ls) + "_vr" + _slug(vr) + "_thr" + _slug(thr)
           + "_env" + _slug(env) + "_grid20x20"
           + "_dr" + _slug(dr) + "_ld" + _slug(ld))
    return tag.lower()


def move_outputs(combo, gpu_id):
    ls, vr, thr, env, dr, ld = combo
    stem = build_stem(ls, vr, thr, env, dr, ld)
    EVAL_DIR.mkdir(parents=True, exist_ok=True)
    moved = []
    for suffix in ("_training.npz", "_dataset.npz"):
        src = RAW_DIR / (stem + suffix)
        if src.exists():
            dst = EVAL_DIR / src.name
            shutil.move(str(src), str(dst))
            moved.append(dst.name)
    if moved:
        print("[GPU " + str(gpu_id) + "] moved -> " + str(EVAL_DIR) + ": "
              + ", ".join(moved), flush=True)
    else:
        print("[GPU " + str(gpu_id) + "] WARNING: no output found to move for "
              + stem, flush=True)
    return stem


def make_cmd(ls, vr, thr, seed, dr, ld):
    return base + [
        "--env-length-scale",        str(ls),
        "--env-var-r",               str(vr),
        "--env-seed-field",          str(seed),
        "--ibm-detection-threshold", str(thr),
        "--disp-rate",               str(dr),
        "--ldd-prob",                str(ld),
    ]


def run_one(cmd, gpu_id):
    env = os.environ.copy()
    env["CUDA_VISIBLE_DEVICES"] = str(gpu_id)
    print("[GPU " + str(gpu_id) + "] >>> "
          + " ".join(shlex.quote(c) for c in cmd), flush=True)
    subprocess.run(cmd, check=True, env=env)


def worker(gpu_id, items):
    for combo, cmd in items:
        try:
            run_one(cmd, gpu_id)
            move_outputs(combo, gpu_id)     # move OUT of results/data
        except subprocess.CalledProcessError as e:
            print("[GPU " + str(gpu_id) + "] [ERROR] " + str(e), flush=True)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--limit", type=int, default=None,
                        help="Run only the first N combos (smoke test)")
    parser.add_argument("--raw-out-dir", default=None,
                        help="override where run_all_rps writes (default RAW_DIR)")
    parser.add_argument("--eval-out-dir", default=None,
                        help="override where worlds are moved (default EVAL_DIR)")
    args = parser.parse_args()
    global RAW_DIR, EVAL_DIR
    if args.raw_out_dir:
        RAW_DIR = Path(args.raw_out_dir)
    if args.eval_out_dir:
        EVAL_DIR = Path(args.eval_out_dir)

    combos = EVAL_COMBOS if args.limit is None else EVAL_COMBOS[:args.limit]
    print("[INFO] eval worlds to generate: " + str(len(combos)))
    print("[INFO] raw dir : " + str(RAW_DIR))
    print("[INFO] eval dir: " + str(EVAL_DIR))
    for i, c in enumerate(combos):
        ls, vr, thr, seed, dr, ld = c
        print("  [" + str(i + 1) + "] ls=" + str(ls) + " vr=" + str(vr)
              + " thr=" + str(thr) + " env=" + str(seed)
              + " dr=" + ("%.0e" % dr) + " ld=" + str(ld))
    cmds = [make_cmd(*p) for p in combos]
    items = list(zip(combos, cmds))
    gpus = get_gpu_list()
    print("[INFO] Using GPUs: " + str(gpus))
    chunks = [items[i::len(gpus)] for i in range(len(gpus))]
    procs = []
    for gpu_id, chunk in zip(gpus, chunks):
        if not chunk:
            continue
        p = Process(target=worker, args=(gpu_id, chunk), daemon=False)
        p.start(); procs.append(p)
    for p in procs:
        p.join()
    print("[INFO] All eval worlds finished (moved into " + str(EVAL_DIR) + ").")


if __name__ == "__main__":
    os.environ.setdefault("USE_GPU", "1")
    main()
